[package]
name = "pixel_demolition_common"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
image = "0.24.6"

[dependencies.web-sys]
version = "0.3.4"
features = [
	"CanvasRenderingContext2d",
]
